### ISSUE TITLE
Custom Pawn-types can't capture normal Pawns en passant

### ISSUE THREAD

**Issue by rapiermother** [fairy-stockfish/Fairy-Stockfish#680] opened 2023-07-09 22:17 UTC
I'm seeing unexpected results when using custom pawn types, in that normal pawns don't seem to trigger en passant when they double-step while using custom pawn types.

To reproduce this issue, here is my variants.ini:

```
# Custom Pawn Variant
[cpvariant:chess]
customPiece1 = f:fsmWfceFifmnD
pawnTypes = pf
startFen = 4k3/pfppppfp/8/8/8/8/PFPPPPFP/4K3 w - - 0 1
pieceToCharTable = KPF...................kpf...................
```

Here is a log showing that the custom pawn does trigger en passant while the normal pawn doesn't. It's also surprising to find _two_ squares listed in the en passant portion of the FEN after the custom pawn's double-step - this could be an additional bug, or it could be expected behaviour _(although I'd like to know which, so I can handle it properly in my code)_.

```
>> setoption name UCI_Variant value cpvariant
<< info string variant cpvariant files 8 ranks 8 pocket 0 template fairy startpos 4k3/pfppppfp/8/8/8/8/PFPPPPFP/4K3 w - - 0 1
>> position startpos moves e2e4
>> d
<< 
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   | k |   |   |   |8 *
<<  +---+---+---+---+---+---+---+---+
<<  | p | f | p | p | p | p | f | p |7
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |6
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |5
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   | P |   |   |   |4
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |3
<<  +---+---+---+---+---+---+---+---+
<<  | P | F | P | P |   | P | F | P |2
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   | K |   |   |   |1  
<<  +---+---+---+---+---+---+---+---+
<<    a   b   c   d   e   f   g   h
<< 
<< Fen: 4k3/pfppppfp/8/8/4P3/8/PFPP1PFP/4K3 b - - 0 1
<< Sfen: 4k3/pfppppfp/8/8/4P3/8/PFPP1PFP/4K3 w - 2
<< Key: D5CADF1195400035
<< Checkers: 
<< Chased: 
>> position startpos moves b2b4
>> d
<< 
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   | k |   |   |   |8 *
<<  +---+---+---+---+---+---+---+---+
<<  | p | f | p | p | p | p | f | p |7
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |6
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |5
<<  +---+---+---+---+---+---+---+---+
<<  |   | F |   |   |   |   |   |   |4
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   |   |   |   |   |3
<<  +---+---+---+---+---+---+---+---+
<<  | P |   | P | P | P | P | F | P |2
<<  +---+---+---+---+---+---+---+---+
<<  |   |   |   |   | K |   |   |   |1  
<<  +---+---+---+---+---+---+---+---+
<<    a   b   c   d   e   f   g   h
<< 
<< Fen: 4k3/pfppppfp/8/8/1F6/8/P1PPPPFP/4K3 b - b3b4 0 1
<< Sfen: 4k3/pfppppfp/8/8/1F6/8/P1PPPPFP/4K3 w - 2
<< Key: E6104F5ACF373B69
<< Checkers: 
<< Chased: 
```

It may be worth noting that I've tested with various tweaks to variants.ini, with no change to the issue:
-added redundant `pawn = p` line
-added redundant `pawn = p:fmWfceFifmnD` line
-added redundant `enPassantTypes = pf` line
-removed `imfnD` from the end of customPiece1's Betza

After further testing:

-`b2b4 e8d8 b4b5 c7c5` doesn't trigger c6 being an en passant target (and as such, `go perft 1` doesn't include `b5c6` in its output, making it an illegal move); _this is an interaction between a stationary custom pawn-type and a moving normal Pawn_.
-`e1d1 b7b5 d1e1 b5b4 c2c4` has the same result, with c3 not being an en passant target, indicating that this is true for Black as well.
-`c2c4 e8d8 c4c5 b7b5` does trigger b6 being an en passant target; _this is an interaction between a moving custom pawn-type and a stationary normal Pawn_.

-`e2e4 e8d8 e4e5 d7d5` does trigger d6 being an en passant target, indicating that normal Pawn/normal Pawn interactions may be unaffected.
-`e1d1 e7e5 d1e1 e5e4 f2f4` does trigger f3 being an en passant target, indicating that this is true for Black as well.

-`b2b4 e8d8 b4a4 d8e8 a4a5 b7b5` does trigger b6 being an en passant target, indicating that custom pawn-type/custom pawn-type interactions may be unaffected.

Conclusions: **A custom pawn-type can't capture a normal Pawn en passant**. As expected, it can capture other custom pawn-types en passant, and normal Pawns can capture both normal Pawns and custom pawn-types en passant.

**Comment by rapiermother** [comment] 2023-07-10 00:21
After further testing:

-`b2b4 e8d8 b4b5 c7c5` doesn't trigger c6 being an en passant target (and as such, `go perft 1` doesn't include `b5c6` in its output, making it an illegal move); _this is an interaction between a stationary custom pawn-type and a moving normal Pawn_.
-`e1d1 b7b5 d1e1 b5b4 c2c4` has the same result, with c3 not being an en passant target, indicating that this is true for Black as well.
-`c2c4 e8d8 c4c5 b7b5` does trigger b6 being an en passant target; _this is an interaction between a moving custom pawn-type and a stationary normal Pawn_.

-`e2e4 e8d8 e4e5 d7d5` does trigger d6 being an en passant target, indicating that normal Pawn/normal Pawn interactions may be unaffected.
-`e1d1 e7e5 d1e1 e5e4 f2f4` does trigger f3 being an en passant target, indicating that this is true for Black as well.

-`b2b4 e8d8 b4a4 d8e8 a4a5 b7b5` does trigger b6 being an en passant target, indicating that custom pawn-type/custom pawn-type interactions may be unaffected.

Conclusions: **A custom pawn-type can't capture a normal Pawn en passant**. As expected, it can capture other custom pawn-types en passant, and normal Pawns can capture both normal Pawns and custom pawn-types en passant.

**Comment by ianfab** [comment] 2023-07-16 14:59
Thanks for reporting, bug is confirmed.

The cause of this issue is that I tried to retain the optimized pawn en passant handling for standard chess, i.e., that the en passant square is only set if capturing is actually possible, while always setting the en passant square for custom pawns to make it work flexible. What apparently was missed was case where the more strict handling should not be applied to standard pawns if other en passant types are present.

I have pushed a [preliminary fix](https://github.com/fairy-stockfish/Fairy-Stockfish/tree/ep), but did not have much time to test it yet.

**Comment by rapiermother** [comment] 2023-07-16 23:16
Hi, thanks for getting back to me.

I'm having some trouble with the link you provided - it seems to bring me
right back to the Fairy Stockfish GitHub page rather than to a fix. I'd
imagine that this is due to a combination of my lack of experience with
GitHub and GitHub's lack of intuitiveness for new visitors. I was hoping
you could point me in the right direction - I'd love to test out the fix.

Thanks :)

**Comment by ianfab** [comment] 2023-07-17 07:56
The link points you to the branch ("ep") where I committed the changes. You should e.g. see there that it is "1 commit ahead" of master, and clicking on that should show the changes.

**Closed** 2023-08-20 09:32 UTC
Labels: bug
